Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyKho.Models;

namespace WebTruyen.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        DataClasses1DataContext data = new DataClasses1DataContext("KISURAAAA\\KIRAAAA");

        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["hoten"];
            var tendangnhap = collection["tendangnhap"];
            var matkhau = collection["matkhau"];
            var MatKhauXacNhan = collection["MatKhauXacNhan"];
            var email = collection["email"];
            var diachi = collection["diachi"];
            var dienthoai = collection["dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["ngaysinh"]);

            if(String.IsNullOrEmpty(MatKhauXacNhan))
            {
                ViewData["NhapMKXN"] = "Bắt buộc phải nhập !!!";
            }
            else
            {
                    kh.hoten = hoten;
                    kh.tendangnhap = tendangnhap;
                    kh.matkhau = matkhau;
                    kh.email = email;
                    kh.diachi = diachi;
                    kh.dienthoai = dienthoai;
                    kh.ngaysinh = DateTime.Parse(ngaysinh);

                    data.KhachHangs.InsertOnSubmit(kh);
                    data.SubmitChanges();

                return RedirectToAction("DangNhap");
            }
            return this.DangKy();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendangnhap = collection["tendangnhap"];
            var matkhau = collection["matkhau"];
            KhachHang kh = data.KhachHangs.SingleOrDefault(n => n.tendangnhap == tendangnhap && n.matkhau == matkhau);
            if( kh != null)
            {
                ViewBag.ThongBao = "Đăng Nhập Thành Công";
                Session["TaiKhoan"] = kh;
            }
            else
            {
                ViewBag.ThongBao = "Sai Tài Khoản Hoặc Mật Khẩu";
            }
            return RedirectToAction("Index", "Home");
        }

    }
}

Controllers/SanPhamController.cs
using QuanLyKho.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        DataClasses1DataContext data = new DataClasses1DataContext("KISURAAAA\\KIRAAAA");
        public ActionResult Index()
        {
            var all_theloai = from tt in data.SanPhams select tt;
            return View(all_theloai);
        }

        //---------------Detail----------------
        public ActionResult Detail(int id)
        {
            var D_sach = data.SanPhams.Where(m => m.masp == id).First();
            return View(D_sach);
        }

        //---------------Create----------------
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, SanPham s)
        {
            var E_tensach = collection["tensp"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngay = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_sl = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tensp = E_tensach.ToString();
                s.hinh = E_hinh.ToString();
                s.giaban = E_giaban;
                s.ngaycapnhat = E_ngay;
                s.soluongton = E_sl;
                data.SanPhams.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }


        //---------------Edit----------------
        public ActionResult Edit(int id)
        {
            var E_sach = data.SanPhams.First(m => m.masp == id);
            return View(E_sach);
        }
        [HttpPost]

        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sach = data.SanPhams.First(m => m.masp == id);
            var E_tensach = collection["tensp"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            E_sach.masp = id;
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Không được bỏ trống!";
            }
            else
            {
                E_sach.tensp = E_tensach;
                E_sach.hinh = E_hinh;
                E_sach.giaban = E_giaban;
                E_sach.ngaycapnhat = E_ngaycapnhat;
                E_sach.soluongton = E_soluongton;
                UpdateModel(E_sach);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }

        //---------------Delete----------------
        public ActionResult Delete(int id)
        {
            var D_sach = data.SanPhams.First(m => m.masp == id);
            return View(D_sach);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = data.SanPhams.Where(m => m.masp == id).First();
            data.SanPhams.DeleteOnSubmit(D_sach);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/TheLoaiSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyKho.Models;

namespace QuanLyKho.Controllers
{
    public class TheLoaiSPController : Controller
    {
        // GET: TheLoaiSP
        DataClasses1DataContext data = new DataClasses1DataContext("KISURAAAA\\KIRAAAA");
        public ActionResult Index()
        {
            var all_theloai = from tt in data.TheLoaiSPs select tt;
            return View(all_theloai);
        }

        public ActionResult Detail(int id)
        {
            var D_theloai = data.TheLoaiSPs.Where(m => m.maloaisp == id).First();
            return View(D_theloai);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, TheLoaiSP tl)
        {
            var ten = collection["tenloaisp"];
            if (string.IsNullOrEmpty(ten))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                tl.tenloaisp = ten;
                data.TheLoaiSPs.InsertOnSubmit(tl);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }
  
        public ActionResult Edit(int id)
        {
            var E_category = data.TheLoaiSPs.First(m => m.maloaisp == id);
            return View(E_category);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var theloai = data.TheLoaiSPs.First(m => m.maloaisp == id);
            var E_tenloai = collection["tenloaisp"];
            theloai.maloaisp = id;
            if (string.IsNullOrEmpty(E_tenloai))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                theloai.tenloaisp = E_tenloai;
                UpdateModel(theloai);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }

        public ActionResult Delete(int id)
        {
            var D_theloai = data.TheLoaiSPs.First(m => m.maloaisp == id);
            return View(D_theloai);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_theloai = data.TheLoaiSPs.Where(m => m.maloaisp == id).First();
            data.TheLoaiSPs.DeleteOnSubmit(D_theloai);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("NHÓM 8.5", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Trang Chủ", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Loại Sản Phẩm", "Index", "TheLoaiSP", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Sản Phẩm", "Index", "SanPham", new { area = "" }, new { @class = "nav-link" })</li>
                    <li></li>
                    <li>@Html.ActionLink("Giỏ Hàng", "GioHang", "GioHang", new { area = "" }, new { @class = "nav-link" })</li>
                    <li></li>
                    <li>@Html.ActionLink("Đăng Nhập", "DangNhap", "NguoiDung", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Đăng Ký", "DangKy", "NguoiDung", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>CÔNG CỤ VÀ MÔI TRƯỜNG PHÁT TRIỂN PHẦM MỀM - NHÓM 8.5 - &copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>